title: Austin Bay
name: Austin Bay

author:
  author__name: Austin Bay
  author__bio: Growth Product
  author__avatar: /assets/images/avatar.jpg

hero:
  hero__title: ğŸ‘‹ğŸ» Hi, I'm Austin.
  hero__description: I work with teams on growth strategies that meet users where they are, spark early insight, and build lasting engagement.
