title: Austin Bay
name: Austin Bay

author:
  author__name: Austin Bay
  author__bio: Growth Product
  author__avatar: /assets/images/avatar.jpg

hero:
  hero__title: ğŸ‘‹ğŸ» Hi, I'm Austin.
  hero__description: I'm a mid-career growth PM living in San Francisco. And this is my digital garden. A collection of field notes and artifacts from my desk to yours.
