title: Austin Bay
name: Austin Bay

author:
  author__name: Austin Bay
  author__bio: Works at the intersection of product and search. Interested in how people find and stick with the things they love.
  author__avatar: /assets/images/avatar.jpg

hero:
  hero__title: ğŸ‘‹ğŸ» Hi, I'm Austin.
  hero__description: I work with teams to create growth strategies that meet users where they are, spark ealy insight, and build lasting engagement.
