title: Austin Bay
name: Austin Bay
color_scheme: auto

author:
  author__name: Austin Bay
  author__bio: Growth Product
  author__avatar: /assets/images/Headshot2.jpg

hero:
  hero__title: ğŸ‘‹ğŸ» Hi, I'm Austin.
  hero__description: I'm a mid-career growth PM living in San Francisco. This is my digital garden. A collection of field notes & artifacts from my desk to yours.
  hero__image: /assets/images/IMG_0316.jpeg
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/austin-bay-2763a918/"}
- {icon: "ion-logo-twitter", link: "https://x.com/austinjbay"}
- {icon: "ion-logo-github", link: "https://github.com/austinjbay"}
- {icon: "ion-logo-tumblr", link: "https://www.tumblr.com/austinjbay"}

google-analytics: G-C3NW59QVPZ
permalink: /:title
