title: Austin Bay
name: Austin Bay

author:
  author__name: Austin Bay
  author__bio: Works at the intersection of product and search. Interested in how people find and stick with the things they love.
  author__avatar: /assets/images/avatar.jpg

hero:
  hero__title: ğŸ‘‹ğŸ» Hi, I'm Austin.
  hero__description: Building things at the intersection of product and search.
  hero__image: /assets/images/avatar.jpg
